// PaymentEventResponseType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/payments/payment_app.mojom
//

package org.chromium.payments.mojom;

public final class PaymentEventResponseType {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int PAYMENT_EVENT_SUCCESS = 0;
    public static final int PAYMENT_EVENT_REJECT = 1; // PAYMENT_EVENT_SUCCESS + 1
    public static final int PAYMENT_EVENT_SERVICE_WORKER_ERROR = 2; // PAYMENT_EVENT_REJECT + 1
    public static final int PAYMENT_HANDLER_WINDOW_CLOSING = 3; // PAYMENT_EVENT_SERVICE_WORKER_ERROR + 1
    public static final int PAYMENT_EVENT_INTERNAL_ERROR = 4; // PAYMENT_HANDLER_WINDOW_CLOSING + 1
    public static final int PAYMENT_EVENT_NO_RESPONSE = 5; // PAYMENT_EVENT_INTERNAL_ERROR + 1
    public static final int PAYMENT_DETAILS_STRINGIFY_ERROR = 6; // PAYMENT_EVENT_NO_RESPONSE + 1
    public static final int PAYMENT_METHOD_NAME_EMPTY = 7; // PAYMENT_DETAILS_STRINGIFY_ERROR + 1
    public static final int PAYMENT_DETAILS_ABSENT = 8; // PAYMENT_METHOD_NAME_EMPTY + 1
    public static final int PAYMENT_DETAILS_NOT_OBJECT = 9; // PAYMENT_DETAILS_ABSENT + 1
    public static final int PAYMENT_EVENT_BROWSER_ERROR = 10; // PAYMENT_DETAILS_NOT_OBJECT + 1
    public static final int PAYMENT_EVENT_TIMEOUT = 11; // PAYMENT_EVENT_BROWSER_ERROR + 1
    public static final int PAYMENT_HANDLER_INSECURE_NAVIGATION = 12; // PAYMENT_EVENT_TIMEOUT + 1
    public static final int PAYER_NAME_EMPTY = 13; // PAYMENT_HANDLER_INSECURE_NAVIGATION + 1
    public static final int PAYER_EMAIL_EMPTY = 14; // PAYER_NAME_EMPTY + 1
    public static final int PAYER_PHONE_EMPTY = 15; // PAYER_EMAIL_EMPTY + 1
    public static final int SHIPPING_ADDRESS_INVALID = 16; // PAYER_PHONE_EMPTY + 1
    public static final int SHIPPING_OPTION_EMPTY = 17; // SHIPPING_ADDRESS_INVALID + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 17;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private PaymentEventResponseType() {}
}