// TrustedUrlRequestParams.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/url_loader.mojom
//

package org.chromium.network.mojom;


public final class TrustedUrlRequestParams extends org.chromium.mojo.bindings.Struct {

    private static final int STRUCT_SIZE = 24;
    private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY = new org.chromium.mojo.bindings.DataHeader[] {new org.chromium.mojo.bindings.DataHeader(24, 0)};
    private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
    public NetworkIsolationKey networkIsolationKey;
    public int updateNetworkIsolationKeyOnRedirect;
    public boolean disableSecureDns;
    public boolean hasUserActivation;

    private TrustedUrlRequestParams(int version) {
        super(STRUCT_SIZE, version);
    }

    public TrustedUrlRequestParams() {
        this(0);
    }

    public static TrustedUrlRequestParams deserialize(org.chromium.mojo.bindings.Message message) {
        return decode(new org.chromium.mojo.bindings.Decoder(message));
    }

    /**
     * Similar to the method above, but deserializes from a |ByteBuffer| instance.
     *
     * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
     */
    public static TrustedUrlRequestParams deserialize(java.nio.ByteBuffer data) {
        return deserialize(new org.chromium.mojo.bindings.Message(
                data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
    }

    @SuppressWarnings("unchecked")
    public static TrustedUrlRequestParams decode(org.chromium.mojo.bindings.Decoder decoder0) {
        if (decoder0 == null) {
            return null;
        }
        decoder0.increaseStackDepth();
        TrustedUrlRequestParams result;
        try {
            org.chromium.mojo.bindings.DataHeader mainDataHeader = decoder0.readAndValidateDataHeader(VERSION_ARRAY);
            final int elementsOrVersion = mainDataHeader.elementsOrVersion;
            result = new TrustedUrlRequestParams(elementsOrVersion);
                {
                    
                org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, true);
                result.networkIsolationKey = NetworkIsolationKey.decode(decoder1);
                }
                {
                    
                result.updateNetworkIsolationKeyOnRedirect = decoder0.readInt(16);
                    UpdateNetworkIsolationKeyOnRedirect.validate(result.updateNetworkIsolationKeyOnRedirect);
                }
                {
                    
                result.disableSecureDns = decoder0.readBoolean(20, 0);
                }
                {
                    
                result.hasUserActivation = decoder0.readBoolean(20, 1);
                }

        } finally {
            decoder0.decreaseStackDepth();
        }
        return result;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected final void encode(org.chromium.mojo.bindings.Encoder encoder) {
        org.chromium.mojo.bindings.Encoder encoder0 = encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);
        
        encoder0.encode(this.networkIsolationKey, 8, true);
        
        encoder0.encode(this.updateNetworkIsolationKeyOnRedirect, 16);
        
        encoder0.encode(this.disableSecureDns, 20, 0);
        
        encoder0.encode(this.hasUserActivation, 20, 1);
    }
}