// AppCacheEventId.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/appcache/appcache.mojom
//

package org.chromium.blink.mojom;

public final class AppCacheEventId {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int APPCACHE_CHECKING_EVENT = 0;
    public static final int APPCACHE_ERROR_EVENT = 1; // APPCACHE_CHECKING_EVENT + 1
    public static final int APPCACHE_NO_UPDATE_EVENT = 2; // APPCACHE_ERROR_EVENT + 1
    public static final int APPCACHE_DOWNLOADING_EVENT = 3; // APPCACHE_NO_UPDATE_EVENT + 1
    public static final int APPCACHE_PROGRESS_EVENT = 4; // APPCACHE_DOWNLOADING_EVENT + 1
    public static final int APPCACHE_UPDATE_READY_EVENT = 5; // APPCACHE_PROGRESS_EVENT + 1
    public static final int APPCACHE_CACHED_EVENT = 6; // APPCACHE_UPDATE_READY_EVENT + 1
    public static final int APPCACHE_OBSOLETE_EVENT = 7; // APPCACHE_CACHED_EVENT + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 7;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private AppCacheEventId() {}
}