// ServiceWorkerResponseError.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/service_worker/service_worker_error_type.mojom
//

package org.chromium.blink.mojom;

public final class ServiceWorkerResponseError {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int UNKNOWN = 0;
    public static final int PROMISE_REJECTED = 1; // UNKNOWN + 1
    public static final int DEFAULT_PREVENTED = 2; // PROMISE_REJECTED + 1
    public static final int NO_V8_INSTANCE = 3; // DEFAULT_PREVENTED + 1
    public static final int RESPONSE_TYPE_ERROR = 4; // NO_V8_INSTANCE + 1
    public static final int RESPONSE_TYPE_OPAQUE = 5; // RESPONSE_TYPE_ERROR + 1
    public static final int RESPONSE_TYPE_NOT_BASIC_OR_DEFAULT = 6; // RESPONSE_TYPE_OPAQUE + 1
    public static final int BODY_USED = 7; // RESPONSE_TYPE_NOT_BASIC_OR_DEFAULT + 1
    public static final int RESPONSE_TYPE_OPAQUE_FOR_CLIENT_REQUEST = 8; // BODY_USED + 1
    public static final int RESPONSE_TYPE_OPAQUE_REDIRECT = 9; // RESPONSE_TYPE_OPAQUE_FOR_CLIENT_REQUEST + 1
    public static final int BODY_LOCKED = 10; // RESPONSE_TYPE_OPAQUE_REDIRECT + 1
    public static final int REDIRECTED_RESPONSE_FOR_NOT_FOLLOW_REQUEST = 11; // BODY_LOCKED + 1
    public static final int DATA_PIPE_CREATION_FAILED = 12; // REDIRECTED_RESPONSE_FOR_NOT_FOLLOW_REQUEST + 1
    public static final int RESPONSE_TYPE_CORS_FOR_REQUEST_MODE_SAME_ORIGIN = 13; // DATA_PIPE_CREATION_FAILED + 1
    public static final int RESPONSE_BODY_BROKEN = 14; // RESPONSE_TYPE_CORS_FOR_REQUEST_MODE_SAME_ORIGIN + 1
    public static final int DISALLOWED_BY_CORP = 15; // RESPONSE_BODY_BROKEN + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 15;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private ServiceWorkerResponseError() {}
}