// MediaSessionAction.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/media_session/public/mojom/media_session.mojom
//

package org.chromium.media_session.mojom;

public final class MediaSessionAction {
    private static final boolean IS_EXTENSIBLE = true;

    public static final int PLAY = 0;
    public static final int PAUSE = 1; // PLAY + 1
    public static final int PREVIOUS_TRACK = 2; // PAUSE + 1
    public static final int NEXT_TRACK = 3; // PREVIOUS_TRACK + 1
    public static final int SEEK_BACKWARD = 4; // NEXT_TRACK + 1
    public static final int SEEK_FORWARD = 5; // SEEK_BACKWARD + 1
    public static final int SKIP_AD = 6; // SEEK_FORWARD + 1
    public static final int STOP = 7; // SKIP_AD + 1
    public static final int SEEK_TO = 8; // STOP + 1
    public static final int SCRUB_TO = 9; // SEEK_TO + 1
    public static final int ENTER_PICTURE_IN_PICTURE = 10; // SCRUB_TO + 1
    public static final int EXIT_PICTURE_IN_PICTURE = 11; // ENTER_PICTURE_IN_PICTURE + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 11;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private MediaSessionAction() {}
}