// VideoCodecProfile.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     gpu/ipc/common/gpu_info.mojom
//

package org.chromium.gpu.mojom;

public final class VideoCodecProfile {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int VIDEO_CODEC_PROFILE_UNKNOWN = -1;
    public static final int H264PROFILE_BASELINE = 0;
    public static final int H264PROFILE_MAIN = 1; // H264PROFILE_BASELINE + 1
    public static final int H264PROFILE_EXTENDED = 2; // H264PROFILE_MAIN + 1
    public static final int H264PROFILE_HIGH = 3; // H264PROFILE_EXTENDED + 1
    public static final int H264PROFILE_HIGH10PROFILE = 4; // H264PROFILE_HIGH + 1
    public static final int H264PROFILE_HIGH422PROFILE = 5; // H264PROFILE_HIGH10PROFILE + 1
    public static final int H264PROFILE_HIGH444PREDICTIVEPROFILE = 6; // H264PROFILE_HIGH422PROFILE + 1
    public static final int H264PROFILE_SCALABLEBASELINE = 7; // H264PROFILE_HIGH444PREDICTIVEPROFILE + 1
    public static final int H264PROFILE_SCALABLEHIGH = 8; // H264PROFILE_SCALABLEBASELINE + 1
    public static final int H264PROFILE_STEREOHIGH = 9; // H264PROFILE_SCALABLEHIGH + 1
    public static final int H264PROFILE_MULTIVIEWHIGH = 10; // H264PROFILE_STEREOHIGH + 1
    public static final int VP8PROFILE_ANY = 11; // H264PROFILE_MULTIVIEWHIGH + 1
    public static final int VP9PROFILE_PROFILE0 = 12; // VP8PROFILE_ANY + 1
    public static final int VP9PROFILE_PROFILE1 = 13; // VP9PROFILE_PROFILE0 + 1
    public static final int VP9PROFILE_PROFILE2 = 14; // VP9PROFILE_PROFILE1 + 1
    public static final int VP9PROFILE_PROFILE3 = 15; // VP9PROFILE_PROFILE2 + 1
    public static final int HEVCPROFILE_MAIN = 16; // VP9PROFILE_PROFILE3 + 1
    public static final int HEVCPROFILE_MAIN10 = 17; // HEVCPROFILE_MAIN + 1
    public static final int HEVCPROFILE_MAIN_STILL_PICTURE = 18; // HEVCPROFILE_MAIN10 + 1
    public static final int DOLBYVISION_PROFILE0 = 19; // HEVCPROFILE_MAIN_STILL_PICTURE + 1
    public static final int DOLBYVISION_PROFILE4 = 20; // DOLBYVISION_PROFILE0 + 1
    public static final int DOLBYVISION_PROFILE5 = 21; // DOLBYVISION_PROFILE4 + 1
    public static final int DOLBYVISION_PROFILE7 = 22; // DOLBYVISION_PROFILE5 + 1
    public static final int THEORAPROFILE_ANY = 23; // DOLBYVISION_PROFILE7 + 1
    public static final int AV1PROFILE_PROFILE_MAIN = 24; // THEORAPROFILE_ANY + 1
    public static final int AV1PROFILE_PROFILE_HIGH = 25; // AV1PROFILE_PROFILE_MAIN + 1
    public static final int AV1PROFILE_PROFILE_PRO = 26; // AV1PROFILE_PROFILE_HIGH + 1
    public static final int DOLBYVISION_PROFILE8 = 27; // AV1PROFILE_PROFILE_PRO + 1
    public static final int DOLBYVISION_PROFILE9 = 28; // DOLBYVISION_PROFILE8 + 1

    public static boolean isKnownValue(int value) {
        return value >= -1 && value <= 28;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private VideoCodecProfile() {}
}