// EventType.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/events/mojom/event_constants.mojom
//

package org.chromium.ui.mojom;

public final class EventType {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int UNKNOWN = 0;
    public static final int KEY_PRESSED = 1; // UNKNOWN + 1
    public static final int KEY_RELEASED = 2; // KEY_PRESSED + 1
    public static final int GESTURE_TAP = 3; // KEY_RELEASED + 1
    public static final int GESTURE_SWIPE = 4; // GESTURE_TAP + 1
    public static final int GESTURE_PINCH_BEGIN = 5; // GESTURE_SWIPE + 1
    public static final int GESTURE_PINCH_END = 6; // GESTURE_PINCH_BEGIN + 1
    public static final int GESTURE_PINCH_UPDATE = 7; // GESTURE_PINCH_END + 1
    public static final int SCROLL = 8; // GESTURE_PINCH_UPDATE + 1
    public static final int SCROLL_FLING_START = 9; // SCROLL + 1
    public static final int SCROLL_FLING_CANCEL = 10; // SCROLL_FLING_START + 1
    public static final int CANCEL_MODE = 11; // SCROLL_FLING_CANCEL + 1
    public static final int MOUSE_PRESSED_EVENT = 12; // CANCEL_MODE + 1
    public static final int MOUSE_DRAGGED_EVENT = 13; // MOUSE_PRESSED_EVENT + 1
    public static final int MOUSE_RELEASED_EVENT = 14; // MOUSE_DRAGGED_EVENT + 1
    public static final int MOUSE_MOVED_EVENT = 15; // MOUSE_RELEASED_EVENT + 1
    public static final int MOUSE_ENTERED_EVENT = 16; // MOUSE_MOVED_EVENT + 1
    public static final int MOUSE_EXITED_EVENT = 17; // MOUSE_ENTERED_EVENT + 1
    public static final int MOUSE_WHEEL_EVENT = 18; // MOUSE_EXITED_EVENT + 1
    public static final int MOUSE_CAPTURE_CHANGED_EVENT = 19; // MOUSE_WHEEL_EVENT + 1
    public static final int TOUCH_RELEASED = 20; // MOUSE_CAPTURE_CHANGED_EVENT + 1
    public static final int TOUCH_PRESSED = 21; // TOUCH_RELEASED + 1
    public static final int TOUCH_MOVED = 22; // TOUCH_PRESSED + 1
    public static final int TOUCH_CANCELLED = 23; // TOUCH_MOVED + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 23;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private EventType() {}
}