// PointerKind.java is auto generated by mojom_bindings_generator.py, do not edit


// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     ui/events/mojom/event_constants.mojom
//

package org.chromium.ui.mojom;

public final class PointerKind {
    private static final boolean IS_EXTENSIBLE = false;

    public static final int UNKNOWN = 0;
    public static final int MOUSE = 1; // UNKNOWN + 1
    public static final int PEN = 2; // MOUSE + 1
    public static final int TOUCH = 3; // PEN + 1
    public static final int ERASER = 4; // TOUCH + 1

    public static boolean isKnownValue(int value) {
        return value >= 0 && value <= 4;
    }

    public static void validate(int value) {
        if (IS_EXTENSIBLE || isKnownValue(value)) return;
        throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
    }

    private PointerKind() {}
}